apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"auth\":\"%s\"},\"https://%s\":{\"auth\":\"%s\"}}}" .Values.global.registry (printf "%s:%s" "robot$order2bs+deploy-bot" "VPnfzAFiGqD98QiWR0Le7c7EAbOabJjd" | b64enc) .Values.global.registry (printf "%s:%s" "robot$order2bs+deploy-bot" "VPnfzAFiGqD98QiWR0Le7c7EAbOabJjd" | b64enc) | b64enc }}
